services:
  auth-db:
    image: mysql:8.0
    container_name: chatapp-auth-db
    env_file:
      - services/auth-service/.env

    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "${AUTH_DB_PORT:-3306}:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - chatapp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chatapp-phpmyadmin
    env_file:
      - services/auth-service/.env
      
    environment:
      PMA_HOST: auth-db
    ports:
      - "8080:80"
    networks:
      - chatapp-network

volumes:
  auth-db-data:


networks:
  chatapp-network:
    driver: bridge
